//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorManagement_Script01
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvironmentSensor
    {
        public int ID { get; set; }
        public Nullable<int> SensorID { get; set; }
        public string Position { get; set; }
        public string BatteryExchangeDate { get; set; }
        public string LatestUploadDate_Temp { get; set; }
        public string LatestUploadDate_Humi { get; set; }
        public string LatestUploadDate_Light { get; set; }
        public string LatestUploadDate_Human { get; set; }
        public string UploadCycle_Temp { get; set; }
        public string UploadCycle_Humi { get; set; }
        public string UploadCycle_Light { get; set; }
        public string UplloadCycle_Human { get; set; }
        public string BaseStationName { get; set; }
        public string Detail { get; set; }
    }
}
