//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorManagement_Script01
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerSensor
    {
        public int ID { get; set; }
        public Nullable<int> SensorID { get; set; }
        public string ConsumerElectronics { get; set; }
        public string Type { get; set; }
        public string LatestUploadDate { get; set; }
        public string BaseStationName { get; set; }
        public string UploadCycle { get; set; }
        public string Detail { get; set; }
    }
}
